
title: Caelie's Website
author: Caelie Moi
email: czmoi@ebnet.org
description: made for cohen's comp sci p class
twitter_username: caeliemoi
github_username:  caeliemoi

show_excerpts: true # set to false to remove excerpts on the homepage
